### ISSUE TITLE
When will the codes will be released?

### ISSUE THREAD

**Issue by Pefect96** [joeyz0z/MeaCap#1]

**Comment by joeyz0z** [comment]
Thanks for your attention! We will release the code within one month.

**Comment by slcheng97** [comment]
Does the author have any plans to release the code? It has already been a month since the last update.

**Comment by joeyz0z** [comment]
I am sorry for not able to promptly to release the code. Now that the submittion of ECCV and ACM MM is over, in the few days, I will gradually clean and release some of MeaCap code.
To speed up availability, I've released a rudimentary version.

**Comment by YannX1e** [comment]
> Does the author have any plans to release the code? It has already been a month since the last update.

We have published our demo code, feel free to raise issue if you have any other problem.
