### ISSUE TITLE
Error during evaluation : TypeError: unsupported operand type(s) for &=: 'bool' and 'str'

### ISSUE THREAD

**Issue by sreelakshminarayanan** [joeyz0z/MeaCap#2]
Thanks  for sharing the code

during evaluation am getting the below error.

Could you please confirm whether below  hugging face model needs to be used or it something else 

  https://huggingface.co/Ultralytics/YOLOv8

Traceback (most recent call last):
  File "/home/ubuntu/MeaCap/models/main.py", line 1287, in <module>
    masked_sentences = detect_keyword(detect_model, batch_name_list, batch_img_list,
  File "/home/ubuntu/MeaCap/models/main.py", line 854, in detect_keyword
    detect_res = model.predict(source=vision_file, save=True)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/ultralytics/engine/model.py", line 267, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 337, in setup_model
    self.model = AutoBackend(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/ultralytics/nn/autobackend.py", line 123, in __init__
    fp16 &= pt or jit or onnx or xml or engine or nn_module or triton  # FP16
TypeError: unsupported operand type(s) for &=: 'bool' and 'str'

Input arguments: 

output file is ../outputs/cbart-large_coco_clip_w1.0_max_insert_label1_insert_mode0_encoder_loss_type0_4keywords.txt
Namespace(batch_size=1, gpu='0', bart='large', refinement_steps=10, adaptive=False, max_refinement_steps=30, max_len=40, temperature=1, repetition_penalty=2, threshold=0, top_k=0, top_p=0.9, decoder_chain=1, do_sample=0, encoder_loss_type=0, dataset='coco_clip', insert_mode=0, max_insert_label=1, num_labels=3, generate_mode=0, masked_lm=0, full_mask=0, w=1.0, num_keywords=4, random_init=0, conzic_sample=True, clip_model='/home/ubuntu/MeaCap/pretrained/clip-vit-large-patch14', img_path='../demo', conzic_top_k=50, alpha=0.2, beta=0.8, use_detect=True, wordnet=False, detect_path='/home/ubuntu/MeaCap/pretrained/YOLOv8', save_path='./conzic_sample_results', use_memory=True, memory_caption_file='../data/memory/coco_clip/train_captions.json', memory_embedding_file='../data/memory/coco_clip/train_embedding.pt', parser_checkpoint='/home/ubuntu/MeaCap/pretrained/flan-t5-base-VG-factual-sg', model_path='/home/ubuntu/MeaCap/checkpoints/CBART_coco', output_file='../outputs/cbart-large_coco_clip_w1.0_max_insert_label1_insert_mode0_encoder_loss_type0_4keywords.txt', log_path='../logs/generate_keywords')

**Comment by sreelakshminarayanan** [comment]
Could you please assist here

**Comment by joeyz0z** [comment]
We have released a new version of MeaCap's code, which is more complete and easier to use. This bug was fixed in the new code, please update to the new version.
