### ISSUE TITLE
There is a duplication of data download links in the project's README file.

### ISSUE THREAD

**Issue by zhaihaotian** [joeyz0z/MeaCap#3]
First of all, thank you very much for your code. However, I have found an issue in the memory bank section during the data preparation stage. The provided links for the preprocessed textual corpus of CC3M, SS1M, COCO, and Flickr30k all point to the same link, resulting in the COCO dataset being downloaded each time. I hope you can fix this issue. Thank you very much!

**Comment by joeyz0z** [comment]
The issue has been fixed, thanks for your kind warning.
