### ISSUE TITLE
Invalid pypi package in requirements.txt

### ISSUE THREAD

**Issue by morninghut** [joeyz0z/MeaCap#5]
The ``sklearn`` package in requirements.txt seems a invaild item. Maybe we could remove it from the file?
https://github.com/joeyz0z/MeaCap/blob/4c399429c7bfec950f6a4c58ea7d4e8d5a38078f/requirements.txt#L2

**Comment by joeyz0z** [comment]
You can install the package via  ` pip install scikit-learn`

**Comment by morninghut** [comment]
Thanks, I can install the package via the command. But if I use ``pip install -r requirements.txt``, since there is a line ``sklearn``, there will end with a error message like this(note: this is not the exact output, but it illustrates the issue):
```
Collecting scikit-learn
  Using cached scikit-learn-1.1.2.tar.gz (7.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [299 lines of output]
```
And I found delete the line ``sklearn~=0.0.post12 `` in requirements.txt can solve the problem. I hope this little modify can give a better environment deployment experience. Thanks for your time and reply.

**Comment by joeyz0z** [comment]
Thanks for your valuable suggestions.  I have removed this line.
