### ISSUE TITLE
Could you please give an introduction of BLIP2Score implement?

### ISSUE THREAD

**Issue by morninghut** [joeyz0z/MeaCap#6]
I believe it is a nice work, but I still don't know how to get BLIP2Score result. 

Could you introduce more detail about how the BLIPSCORE metric is calculated and implemented? Thank you very much.

**Comment by joeyz0z** [comment]
The Section. C in our appendix has elaborated on the implementation of BLIP2Score. 
![image](https://github.com/user-attachments/assets/fc4003b3-6b63-46a6-952a-634200d46370)
The code of BLIP2Score can refer to [LAVIS example](https://github.com/salesforce/LAVIS/blob/3446bac20c5646d35ae383ebe6d13cec4f8b00cb/examples/blip2_image_text_matching.ipynb).

**Comment by morninghut** [comment]
Thank you for your generous reply! It is very helpful to me.
