### ISSUE TITLE
Bug: args.prompt_ensembling incorrectly specified

### ISSUE THREAD

**Issue by morninghut** [joeyz0z/MeaCap#7]
## Problem Description
When trying to run Training-free inference following the README, I encountered the following issues:
1. I printed the value of args.prompt_ensembling at the end of args.py:
``` 
...
args = parser.parse_args()
print(f"args.prompt_ensembling: {args.prompt_ensembling}")
```

2. Following the README, I ran inference.py with the parameters as follows:
``` 
python inference.py --use_prompt True --prompt_ensembling False --memory_id cc3m --img_path ./image_example --lm_model_path ./checkpoints/CBART_one_billion
```
Please note that, the passed argument args.prompt_ensembling was explicitly defined as False.

3. I got the following output:
```
args.prompt_ensembling: True
...
```

## Analysis
I believe this is caused by a BUG resulting from passing string arguments using `type=bool`. Because in reality, argparse does not convert the string "False" into boolean value False at this point. Instead, it simply uses built-in function `bool` for processing: non-empty means True. Therefore, any non-empty string input will cause args.prompt_ensembling to be True.

## Verification
I passed an empty value to args.prompt_ensembling to verify my hypothesis:
``` 
python inference.py --use_prompt True --prompt_ensembling "" --memory_id cc3m --img_path ./image_example --lm_model_path ./checkpoints/CBART_one_billion
```
And received output:
```
args.prompt_ensembling: False
```

## Conclusion
Therefore, in order to achieve args.prompt_ensembleing: False, it should either be left unspecified or an empty value should be passed instead of passing False.

**Comment by joeyz0z** [comment]
I didn't notice this bug before. Thanks for your valuable suggestions. To fix this bug, I have changed the corresponding code.
`    parser.add_argument("--prompt_ensembling", action='store_true', default=False)`
Now default value of prompt_ensembleing is False, and you can set prompt_ensembleing=True by `--prompt_ensembling`

**Comment by morninghut** [comment]
Thank you for your prompt reply. The bug has been resolved.
